apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: middle-school-math-api-ingress
  labels:
    app.kubernetes.io/name: middle-school-math-api
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: middle-school-math-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 8282
