apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: middle-school-math-api-chroma
  labels:
    app.kubernetes.io/name: middle-school-math-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
